export const data = [
  {
    number: 1,
    product_code: '00154ZS',
    product_name: 'Ноутбук ASUS',
    unit: 'шт.',
    quantity_fact: 99,
    quantity_account: 100,
    quantity_package_fact: 1,
    quantity_package_account: 1,
    price_for_unit: 50000,
    total_sum_fact: 4950000,
    total_sum_account: 5000000,
  },
  {
    number: 2,
    product_code: '05154FE',
    product_name: 'Мышка HP',
    unit: 'шт.',
    quantity_fact: 20,
    quantity_account: 20,
    quantity_package_fact: 1,
    quantity_package_account: 1,
    price_for_unit: 7000,
    total_sum_fact: 140000,
    total_sum_account: 140000,
  },
  {
    number: 3,
    product_code: '43554XW',
    product_name: 'Клавиатура Hyper X',
    unit: 'шт.',
    quantity_fact: 10,
    quantity_account: 10,
    quantity_package_fact: 1,
    quantity_package_account: 1,
    price_for_unit: 10000,
    total_sum_fact: 10000,
    total_sum_account: 100000,
  },
];
