export const data = [
  {
    number: 1,
    component: 'ТТГ',
    result: '4.72',
    unit: 'мкME/мл',
    normal: '0,4-3,77',
    comment: 'Выше нормы',
  },
  {
    number: 2,
    component: 'Свободный Т3',
    result: '1',
    unit: 'пг/мл',
    normal: '2,00-4,40',
    comment: 'Ниже нормы',
  },
  {
    number: 3,
    component: 'Свободный Т4',
    result: '0.92',
    unit: 'нг/мл',
    normal: '1,00-1,70',
    comment: 'Ниже нормы',
  },
  {
    number: 4,
    component: 'Анти ТПО',
    result: '16',
    unit: 'МЕ/мл',
    normal: '0-34',
    comment: 'Норма',
  },
  {
    number: 5,
    component: 'Анти ТГ',
    result: '10',
    unit: 'МЕ/мл',
    normal: '0-115',
    comment: 'Норма',
  },
  {
    number: 6,
    component: 'ПСА общий',
    result: '1.06',
    unit: 'нг/мл',
    normal: '0,000-2,000',
    comment: 'Норма',
  },
  {
    number: 7,
    component: 'Индекс свободного ПСА',
    result: '1',
    unit: '%',
    normal: '15-100',
    comment: 'Ниже нормы',
  },
  {
    number: 8,
    component: 'ПСА свободный',
    result: '1',
    unit: 'нг/мл',
    normal: '',
    comment: 'Норма',
  },
  {
    number: 9,
    component: 'Тиреоглобулин',
    result: '1.53',
    unit: 'нг/мл',
    normal: '1,4-78',
    comment: 'Норма',
  },
];